kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ondemand-sidecar-injector-role
rules:
- apiGroups: ["", "apps"]
  resources: ["deployments", "pods"]
  verbs: ["get", "list", "update"]